# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'pg', '~> 0.18.4'
gem 'vkontakte_api', '~> 1.4', '>= 1.4.4'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'sequel', '~> 5.31'
gem 'requests', '~> 1.0'
gem "telegram-bot-ruby"
